<a href="https://colab.research.google.com/github/KIMJONGIK/Colab/blob/main/Q300.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#001 ~ 010

In [ ]:
data = [1,2,3]
data = np.array(data)
data

array([1, 2, 3])

In [ ]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr = np.arange(3,30,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
np.arange(0,1000, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [ ]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
data = [0, 1, 2, 3, 4, 5]
data = np.array(data)
data.reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
data = [0, 1, 2, 3, 4, 5]
data = np.array(data)
data.reshape(-1,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.reshape(-1)

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.reshape(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.flatten()

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [ ]:
arr.reshape(3,1)

array([[0],
       [1],
       [2]])

#011~020

In [ ]:
np.arange(6).reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.ones(20, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones(20, dtype=int).reshape(4,-1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.ones(100, dtype=int).reshape(10, -1)*255

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.arange(1,4,1, dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [ ]:
data = [1,2,3]
arr = np.ndarray(data, dtype=np.int32)
arr

array([[[42704416,        0,        0],
        [       0,        0,        0]]], dtype=int32)

In [ ]:
arr = np.array(['1', '2', '3'])
print(arr.dtype)

<U1


In [ ]:
arr = np.array([1,2,3])
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

In [ ]:
a = np.array( [ 255, 300, 128], dtype=np.uint8 )
a

array([255,  44, 128], dtype=uint8)

#021~030

In [3]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
arr2 = arr.astype(np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [4]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])