<a href="https://colab.research.google.com/github/KIMJONGIK/Colab/blob/main/Q300.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#001 ~ 010

In [2]:
data = [1,2,3]
data = np.array(data)
data

array([1, 2, 3])

In [3]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
arr = np.arange(3,30,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
np.arange(0,1000, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [6]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [7]:
data = [0, 1, 2, 3, 4, 5]
data = np.array(data)
data.reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
data = [0, 1, 2, 3, 4, 5]
data = np.array(data)
data.reshape(-1,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.reshape(-1)

array([0, 1, 2, 3, 4, 5])

In [10]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.reshape(6)

array([0, 1, 2, 3, 4, 5])

In [11]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.flatten()

array([0, 1, 2, 3, 4, 5])

In [12]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [13]:
arr.reshape(3,1)

array([[0],
       [1],
       [2]])

#011~020

In [14]:
np.arange(6).reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
np.ones(20, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.ones(20, dtype=int).reshape(4,-1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.ones(100, dtype=int).reshape(10, -1)*255

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.arange(1,4,1, dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [20]:
data = [1,2,3]
arr = np.ndarray(data, dtype=np.int32)
arr

array([[[31232512,        0,        0],
        [       0,        0,        0]]], dtype=int32)

In [21]:
arr = np.array(['1', '2', '3'])
print(arr.dtype)

<U1


In [22]:
arr = np.array([1,2,3])
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

In [23]:
a = np.array( [ 255, 300, 128], dtype=np.uint8 )
a

array([255,  44, 128], dtype=uint8)

#021~030

In [24]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
arr2 = arr.astype(np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [25]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [26]:
arr = np.arange(9).reshape(3, 3)
arr[2:]

array([[6, 7, 8]])

In [27]:
arr = np.arange(9).reshape(3, 3)
arr[2:3]

array([[6, 7, 8]])

In [28]:
arr = np.arange(9).reshape(3, 3)
arr[2]

array([6, 7, 8])

In [29]:
arr = np.arange(9).reshape(3, 3)
arr[-1]

array([6, 7, 8])

In [30]:
arr = np.arange(9).reshape(3, 3)
arr[-1:]

array([[6, 7, 8]])

In [31]:
arr = np.arange(25).reshape(5, 5)
arr[3,2]

17

In [32]:
arr = np.arange(25).reshape(5, 5)
arr[3][2]

17

In [33]:
arr = np.arange(25).reshape(5, 5)
arr[1,1:5]

array([6, 7, 8, 9])

In [34]:
arr = np.arange(25).reshape(5, 5)
arr[1,1:]

array([6, 7, 8, 9])

In [35]:
arr = np.arange(25).reshape(5, 5)
arr[:,0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [36]:
arr = np.arange(25).reshape(5, 5)
arr[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [37]:
arr = np.arange(25).reshape(5, 5)
arr[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [38]:
arr = np.arange(25).reshape(5, 5)
arr[[0,4]][:,[0,3]]

array([[ 0,  3],
       [20, 23]])

#031~040

In [39]:
data = [1, 2, 3]
arr = np.array(data) * 10
arr

array([10, 20, 30])

In [40]:
data = [1, 2, 3]
arr = np.array(data)**2
arr

array([1, 4, 9])

In [41]:
data = [1, 2, 3]
arr = np.array(data) * np.array(data)
arr

array([1, 4, 9])

In [42]:
data = [1, 2, 3]
arr = np.sqrt(data)
arr

array([1.        , 1.41421356, 1.73205081])

In [43]:
data = [1, 2, 3]
arr = np.array(data) ** 0.5
arr

array([1.        , 1.41421356, 1.73205081])

In [44]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
score.mean(axis=0)

array([12., 18.])

In [45]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
score.std(axis=1)

array([5., 1.])

In [46]:
a = np.arange(   4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)
a@b

array([[ 3,  4],
       [11, 16]])

In [47]:
a = np.arange(   4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)
np.matmul(a,b)

array([[ 3,  4],
       [11, 16]])

In [48]:
arr = np.arange(10)
arr[arr%2==0]

array([0, 2, 4, 6, 8])

In [49]:
arr = np.arange(10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [50]:
arr = np.arange(10)
arr[ (arr>3) & (arr<7) ]

array([4, 5, 6])

#041~050

In [51]:
arr = np.array([-1, 2, -3, 4])
arr[arr<0]

array([-1, -3])

In [52]:
arr = np.array([-1, 2, -3, 4])
np.abs(arr)

array([1, 2, 3, 4])

In [53]:
abs(arr)

array([1, 2, 3, 4])

In [54]:
arr[arr<0] = -arr[arr<0]
arr

array([1, 2, 3, 4])

In [55]:
arr = np.array([-1, 2, -3, 4])
arr[arr>=0] = arr[arr>=0] +10
arr[arr<0] = arr[arr<0] -10
arr

array([-11,  12, -13,  14])

In [56]:
arr = np.array([-1, 2, -3, 4])
np.where(arr >= 0, arr + 10, arr - 10)

array([-11,  12, -13,  14])

In [57]:
arr = [1, 2, 3, 4, 5]
np.random.choice(arr,5, replace=False)

array([5, 1, 3, 2, 4])

In [58]:
arr = np.array([1, 2, 3, 4, 5])
np.argmin(arr)

0

In [59]:
arr = np.array([1, 2, 3, 4, 5])
np.argmax(arr)

4

In [60]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr.sort()
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
np.vstack([arr1,arr2])

array([[1, 2],
       [3, 4]])

In [63]:
arr = np.array([ [1, 2], [3, 4] ])
arr.flatten()

array([1, 2, 3, 4])

#051~060

In [64]:
import pandas as pd
from pandas import Series

In [65]:
data = [100, 200, 300]
s = Series(data)
print(s)

0    100
1    200
2    300
dtype: int64


In [66]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s)

철수    100
영희    200
아름    300
dtype: int64


In [67]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data)
print(s)
s.index = index
print(s)

0    100
1    200
2    300
dtype: int64
철수    100
영희    200
아름    300
dtype: int64


In [68]:
score = {
    "철수": 100,
    "영희": 200,
    "아름": 300
}

s = Series(score)
print(s)

철수    100
영희    200
아름    300
dtype: int64


In [69]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.index)

Index(['철수', '영희', '아름'], dtype='object')


In [70]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.values)

[100 200 300]


In [71]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.to_dict())

{'철수': 100, '영희': 200, '아름': 300}


In [72]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
s.to_excel('data.xlsx')

In [73]:
data = pd.read_excel('data.xlsx', index_col=0)[0]
data

철수    100
영희    200
아름    300
Name: 0, dtype: int64

#061~070

In [74]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.dtype)

int64


In [75]:
data = [  10,  "가" ]
s = Series( data )
print(s.dtype)

object


In [76]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.index.dtype)

object


In [77]:
data = {
    "2020-12-11": 73400,
    "2020-12-10": 72900,
    "2020-12-09": 73900,
    "2020-12-08": 71700,
    "2020-12-07": 72900
}
s = Series(data)
s.name = "종가"
s.index.name = "날짜"
s

날짜
2020-12-11    73400
2020-12-10    72900
2020-12-09    73900
2020-12-08    71700
2020-12-07    72900
Name: 종가, dtype: int64

In [78]:
data = {"apple": 1500, "banana": 3000}
s = pd.Series(data)
s.to_dict()

{'apple': 1500, 'banana': 3000}

In [79]:
data = {"apple": 1500, "banana": 3000}
s = pd.Series(data)
s.index.name='icecream'
s

icecream
apple     1500
banana    3000
dtype: int64

In [80]:
s = pd.Series(data=[1, 2, 3])
s.name = 'number'
s

0    1
1    2
2    3
Name: number, dtype: int64

In [81]:
s = pd.Series(data=[1, 2, np.NaN])
s

0    1.0
1    2.0
2    NaN
dtype: float64

In [82]:
s = pd.Series([1, 2, 3])
np.array(s.index)

array([0, 1, 2])

In [83]:
s = pd.Series([1, 2, 3])
print(s)
s.array

0    1
1    2
2    3
dtype: int64


<PandasArray>
[1, 2, 3]
Length: 3, dtype: int64

#071~080

In [84]:
s = pd.Series([1, 2, 'python'])
print(s.dtype)

object


In [88]:
s = pd.Series(['1', '2', '3'])
s.astype('int32')

0    1
1    2
2    3
dtype: int32

In [89]:
tickers = ["BTC", "XRP", "ETH"]
prices = [50000, 1, 4000]

s = Series(data=prices, index=tickers, dtype='float')
s

BTC    50000.0
XRP        1.0
ETH     4000.0
dtype: float64

In [91]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data=data, index=index)
s['영희']

200

In [92]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data=data, index=index)
s.iloc[1]

200

In [93]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data=data, index=index)
s.loc['영희']

200

In [96]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data=data, index=index)
s.영희

200

In [108]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data=data, index=index)

print(s.iloc[0:2])
print(s.iloc[:2])
print(s.loc["철수":"영희"])
print(s.loc[:'영희'])
print(s[0:2])
print(s[ :2])
print(s["철수":"영희"])
print(s[:"영희"])
print(s.values[:2])

철수    100
영희    200
dtype: int64
철수    100
영희    200
dtype: int64
철수    100
영희    200
dtype: int64
철수    100
영희    200
dtype: int64
철수    100
영희    200
dtype: int64
철수    100
영희    200
dtype: int64
철수    100
영희    200
dtype: int64
철수    100
영희    200
dtype: int64
[100 200]


In [114]:
data = [100, 200, 300, 400, 500, 600]
index = ["08/01", "08/02", "08/03", "08/04", "08/05", "08/06"]
s = Series(data=data, index=index)

print(s.index[:3])
print(s[:3].index)

Index(['08/01', '08/02', '08/03'], dtype='object')
Index(['08/01', '08/02', '08/03'], dtype='object')


In [127]:
data = [100, 200, 300, 400, 500, 600] 
index = ["08/01", "08/02", "08/03", "08/04", "08/05", "08/06"] 
s = Series(data=data, index=index)

print(s.iloc[::2])
print(s.iloc[1::2])
print(s.iloc[[0, 2, 4]])

print(s[["08/01", "08/03", "08/05"]])
print(s["08/02":"08/05":2])
print(s[:"08/05":2])
print(s["08/01"::2])
print(s[::2])

08/01    100
08/03    300
08/05    500
dtype: int64
08/02    200
08/04    400
08/06    600
dtype: int64
08/01    100
08/03    300
08/05    500
dtype: int64
08/01    100
08/03    300
08/05    500
dtype: int64
08/02    200
08/04    400
dtype: int64
08/01    100
08/03    300
08/05    500
dtype: int64
08/01    100
08/03    300
08/05    500
dtype: int64
08/01    100
08/03    300
08/05    500
dtype: int64


#081~090

In [128]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data=data, index=index)
s['순이']=400
s

철수    100
영희    200
아름    300
순이    400
dtype: int64

In [133]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data=data, index=index)
s.drop('철수')

영희    200
아름    300
dtype: int64

In [134]:
s

철수    100
영희    200
아름    300
dtype: int64

In [135]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data=data, index=index)
s.drop('철수', inplace=True)
s

영희    200
아름    300
dtype: int64

In [137]:
#unique
data = {
    "삼성전자": "전기,전자",
    "LG전자": "전기,전자",
    "현대차": "운수장비",
    "NAVER": "서비스업",
    "카카오": "서비스업"
}
s = Series(data)
s.unique()

array(['전기,전자', '운수장비', '서비스업'], dtype=object)

In [138]:
s = pd.Series(
    data = [9000, 9000, 8000, 9000, 10000],
    index = ['김과장', '이대리', '박전무', '이대리', '이대리']
)
s.unique()

array([ 9000,  8000, 10000])

In [141]:
s = pd.Series(
    data = [9000, 9000, 8000, 9000, 10000],
    index = ['김과장', '이대리', '박전무', '이대리', '이대리']
)
s.value_counts()

9000     3
8000     1
10000    1
dtype: int64

In [144]:
data = {
    "삼성전자": "전기,전자",
    "LG전자": "전기,전자",
    "현대차": "운수장비",
    "NAVER": "서비스업",
    "카카오": "서비스업"
}
s = Series(data)
s.value_counts()

전기,전자    2
서비스업     2
운수장비     1
dtype: int64

In [145]:
data = {
    "매출액":300,
    "PER":np.nan,
    "PBR":2.0
}
s = Series(data)
s

매출액    300.0
PER      NaN
PBR      2.0
dtype: float64

#091~100

In [147]:
data = [100, 300, 200]
index = ["08/01", "08/02", "08/03"]
s = Series(data, index)
print(s.iloc[ [0, 2, 1]])
print(s.loc[ ["08/01", "08/03", "08/02"]])

08/01    100
08/03    200
08/02    300
dtype: int64
08/01    100
08/03    200
08/02    300
dtype: int64


In [149]:
data = np.random.randint(10, size=4)
s = Series(data)
s.sort_values()

0    0
2    6
1    7
3    8
dtype: int64

In [150]:
s.sort_values(ascending=False)

3    8
1    7
2    6
0    0
dtype: int64

In [153]:
s = Series(np.random.randint(10, size=4), ["b", "c", "a", "d"])
s.sort_index()

a    5
b    6
c    3
d    8
dtype: int64

In [155]:
data = [100, 300, 200]
s = Series(data)
s**4

0     100000000
1    8100000000
2    1600000000
dtype: int64

In [161]:
np.power(s,4)

0     100000000
1    8100000000
2    1600000000
dtype: int64

In [166]:
data = [100, 300, 200]
s0 = Series(data, ["a", "c", "b"])
s1 = Series(data, ["a", "b", "c"])
print(s0 + s1)

a    200
b    500
c    500
dtype: int64


In [168]:
s = Series(data=[51500, 51200, 52500], index=["5/1", "5/2", "5/3"])
조건 = s < 52000
s[조건]

5/1    51500
5/2    51200
dtype: int64

In [169]:
s[s<52000]

5/1    51500
5/2    51200
dtype: int64

In [170]:
s = Series(data=[51500, 51200, 52500], index=["5/1", "5/2", "5/3"])
s[s.index > '5/1']

5/2    51200
5/3    52500
dtype: int64

In [172]:
s = Series(data=[51500, 51200, 52500], index=["5/1", "5/2", "5/3"])
s[(s>=51400) & (s<=53000)]

5/1    51500
5/3    52500
dtype: int64

In [181]:
s = Series(data=[51500, 51200, 52500], index=["5/1", "5/2", "5/3"])
s[s<=52000].index.tolist()

['5/1', '5/2']

#101~110

In [185]:
data = {
    '2020-12-11':73400,
    '2020-12-10':72900,
    '2020-12-09':73900,
    '2020-12-08':71700,
    '2020-12-07':72900
}
s = Series(data)
s.sum()

364800

In [186]:
data = {
    '2020-12-11':73400,
    '2020-12-10':72900,
    '2020-12-09':73900,
    '2020-12-08':71700,
    '2020-12-07':72900
}
s = Series(data)
s.mean()

72960.0

In [187]:
data = {
    '2020-12-11':1.01,
    '2020-12-10':0.99,
    '2020-12-09':1.03,
    '2020-12-08':1.02,
    '2020-12-07':1
}
s = Series(data)
s.product()

1.05049494

In [188]:
data = {
    '2020-12-11':73400,
    '2020-12-10':72900,
    '2020-12-09':73900,
    '2020-12-08':71700,
    '2020-12-07':72900
}
s = Series(data)
print(s.max())
print(s.min())

73900
71700


In [189]:
s.pct_change()

2020-12-11         NaN
2020-12-10   -0.006812
2020-12-09    0.013717
2020-12-08   -0.029770
2020-12-07    0.016736
dtype: float64

In [191]:
s.cummax()

2020-12-11    73400
2020-12-10    73400
2020-12-09    73900
2020-12-08    73900
2020-12-07    73900
dtype: int64

In [192]:
s.cummin()

2020-12-11    73400
2020-12-10    72900
2020-12-09    72900
2020-12-08    71700
2020-12-07    71700
dtype: int64

In [193]:
s.cumprod()

2020-12-11                  73400
2020-12-10             5350860000
2020-12-09        395428554000000
2020-12-08   -8541260825619103232
2020-12-07   -6514723640420366336
dtype: int64

In [197]:
s.rolling(window=1).mean()

2020-12-11    73400.0
2020-12-10    72900.0
2020-12-09    73900.0
2020-12-08    71700.0
2020-12-07    72900.0
dtype: float64

In [198]:
s.rolling(window=2).mean()

2020-12-11        NaN
2020-12-10    73150.0
2020-12-09    73400.0
2020-12-08    72800.0
2020-12-07    72300.0
dtype: float64

In [201]:
s.rolling(window=2).sum()/2

2020-12-11        NaN
2020-12-10    73150.0
2020-12-09    73400.0
2020-12-08    72800.0
2020-12-07    72300.0
dtype: float64

#111~120

In [208]:
data = [1, 2, 3, 4, np.nan]
s = Series(data=data)
s.count()

4

In [213]:
s.isna().value_counts()

False    4
True     1
dtype: int64

In [214]:
data = ["100", "200", "300"]
index = ["철수", "영희", "아름"]
s = Series(data, index)
s.astype(np.int32)

철수    100
영희    200
아름    300
dtype: int32

In [217]:
data = ["100,000", "200,000", "300,000"]
index = ["철수", "영희", "아름"]
s = Series(data, index)
s.str.replace(',', '').astype(np.int32)

철수    100000
영희    200000
아름    300000
dtype: int32

In [224]:
s = pd.Series(["30세", "40세", "50세"], index=["김대리", "이과장", "박차장"])
s.str.replace('세','').astype(np.int32)

김대리    30
이과장    40
박차장    50
dtype: int32

In [227]:
s = pd.Series([1, 2, 3, 4], index=["d", "c", "a", "b"])
s.reindex(['a','b', 'c', 'd'])

a    3
b    4
c    2
d    1
dtype: int64

In [230]:
s = pd.Series([1, 2, 3, 4], index=["d", "c", "a", "b"])
s.reindex(s.index.sort_values())

a    3
b    4
c    2
d    1
dtype: int64

In [231]:
s = pd.Series([1, 2, 3])
s.tolist()

[1, 2, 3]

In [232]:
list(s)

[1, 2, 3]

In [234]:
s = pd.Series([1, 2, 3])
s.to_dict()

{0: 1, 1: 2, 2: 3}

In [235]:
dict(s)

{0: 1, 1: 2, 2: 3}

In [237]:
s = pd.Series([1, 2, 3, np.nan])
s.dropna()

0    1.0
1    2.0
2    3.0
dtype: float64

In [251]:
s = pd.Series(["1,234", "5,678", "9,876"])
def a(x):
  return x.replace(",", "")
s.map(a)

0    1234
1    5678
2    9876
dtype: object

In [252]:
s = pd.Series(["1,234", "5,678", "9,876"])
s.map(lambda x:x.replace(',',''))

0    1234
1    5678
2    9876
dtype: object

In [253]:
s = pd.Series([10, 100, 1000])
s.apply(np.log10)

0    1.0
1    2.0
2    3.0
dtype: float64

#121~130

In [254]:
data = [1, 2, 3, 4, np.nan]
s = Series(data=data)
s.dropna()

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

In [255]:
data = range(1, 11)
s = Series(data=data)
s.nlargest(3)

9    10
8     9
7     8
dtype: int64

In [256]:
data = range(1, 11)
s = Series(data=data)
s.nsmallest(3)

0    1
1    2
2    3
dtype: int64

In [259]:
from datetime import datetime
s = pd.Series([datetime(2020,1,1), datetime(2021,1,1), datetime(2022,1,1)])
s.dt.year

0    2020
1    2021
2    2022
dtype: int64

In [263]:
index = [datetime(2020,1,1), datetime(2021,1,1), datetime(2022,1,1)]
data = [100, 200, 300]
s = pd.Series(data=data, index=index)
s.index.year.tolist()

[2020, 2021, 2022]

In [264]:
s = pd.Series([datetime(2022,1,1), datetime(2022,1,2), datetime(2022,1,3)])
s.dt.day

0    1
1    2
2    3
dtype: int64

In [267]:
index = [datetime(2020,1,1), datetime(2021,1,1), datetime(2022,1,1)]
data = [100, 200, 300]
s = pd.Series(data=data, index=index)
s.index.strftime("%Y-%m-%d 00:00:00")

Index(['2020-01-01 00:00:00', '2021-01-01 00:00:00', '2022-01-01 00:00:00'], dtype='object')

In [269]:
s = pd.Series(["000020", "000040", "005930"])
s.str.cat(sep=';')

'000020;000040;005930'

In [270]:
s = pd.Series(["000020", "000040", "005930"])
'A'+s

0    A000020
1    A000040
2    A005930
dtype: object

#101~110