<a href="https://colab.research.google.com/github/KIMJONGIK/Colab/blob/main/Q300.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

#001 ~ 010

In [4]:
data = [1,2,3]
data = np.array(data)
data

array([1, 2, 3])

In [5]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
arr = np.arange(3,30,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
np.arange(0,1000, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [8]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [9]:
data = [0, 1, 2, 3, 4, 5]
data = np.array(data)
data.reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
data = [0, 1, 2, 3, 4, 5]
data = np.array(data)
data.reshape(-1,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.reshape(-1)

array([0, 1, 2, 3, 4, 5])

In [12]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.reshape(6)

array([0, 1, 2, 3, 4, 5])

In [13]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.flatten()

array([0, 1, 2, 3, 4, 5])

In [14]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [15]:
arr.reshape(3,1)

array([[0],
       [1],
       [2]])

#011~020

In [16]:
np.arange(6).reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
np.ones(20, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
np.ones(20, dtype=int).reshape(4,-1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.ones(100, dtype=int).reshape(10, -1)*255

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.arange(1,4,1, dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [22]:
data = [1,2,3]
arr = np.ndarray(data, dtype=np.int32)
arr

array([[[39809472,        0,        0],
        [       0,        0,        0]]], dtype=int32)

In [23]:
arr = np.array(['1', '2', '3'])
print(arr.dtype)

<U1


In [24]:
arr = np.array([1,2,3])
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

In [25]:
a = np.array( [ 255, 300, 128], dtype=np.uint8 )
a

array([255,  44, 128], dtype=uint8)

#021~030

In [26]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
arr2 = arr.astype(np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [27]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [30]:
arr = np.arange(9).reshape(3, 3)
arr[2:]

array([[6, 7, 8]])

In [39]:
arr = np.arange(9).reshape(3, 3)
arr[2:3]

array([[6, 7, 8]])

In [32]:
arr = np.arange(9).reshape(3, 3)
arr[2]

array([6, 7, 8])

In [36]:
arr = np.arange(9).reshape(3, 3)
arr[-1]

array([6, 7, 8])

In [43]:
arr = np.arange(9).reshape(3, 3)
arr[-1:]

array([[6, 7, 8]])

In [44]:
arr = np.arange(25).reshape(5, 5)
arr[3,2]

17

In [46]:
arr = np.arange(25).reshape(5, 5)
arr[3][2]

17

In [48]:
arr = np.arange(25).reshape(5, 5)
arr[1,1:5]

array([6, 7, 8, 9])

In [50]:
arr = np.arange(25).reshape(5, 5)
arr[1,1:]

array([6, 7, 8, 9])

In [52]:
arr = np.arange(25).reshape(5, 5)
arr[:,0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [53]:
arr = np.arange(25).reshape(5, 5)
arr[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [56]:
arr = np.arange(25).reshape(5, 5)
arr[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [80]:
arr = np.arange(25).reshape(5, 5)
arr[[0,4]][:,[0,3]]

array([[ 0,  3],
       [20, 23]])

#031~040

In [87]:
data = [1, 2, 3]
arr = np.array(data) * 10
arr

array([10, 20, 30])

In [90]:
data = [1, 2, 3]
arr = np.array(data)**2
arr

array([1, 4, 9])

In [91]:
data = [1, 2, 3]
arr = np.array(data) * np.array(data)
arr

array([1, 4, 9])

In [95]:
data = [1, 2, 3]
arr = np.sqrt(data)
arr

array([1.        , 1.41421356, 1.73205081])

In [98]:
data = [1, 2, 3]
arr = np.array(data) ** 0.5
arr

array([1.        , 1.41421356, 1.73205081])

In [100]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
score.mean(axis=0)

array([12., 18.])

In [102]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
score.std(axis=1)

array([5., 1.])

In [105]:
a = np.arange(   4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)
a@b

array([[ 3,  4],
       [11, 16]])

In [106]:
a = np.arange(   4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)
np.matmul(a,b)

array([[ 3,  4],
       [11, 16]])

In [109]:
arr = np.arange(10)
arr[arr%2==0]

array([0, 2, 4, 6, 8])

In [110]:
arr = np.arange(10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [112]:
arr = np.arange(10)
arr[ (arr>3) & (arr<7) ]

array([4, 5, 6])

#041~050

In [113]:
arr = np.array([-1, 2, -3, 4])
arr[arr<0]

array([-1, -3])

In [114]:
arr = np.array([-1, 2, -3, 4])
np.abs(arr)

array([1, 2, 3, 4])

In [115]:
abs(arr)

array([1, 2, 3, 4])

In [116]:
arr[arr<0] = -arr[arr<0]
arr

array([1, 2, 3, 4])

In [118]:
arr = np.array([-1, 2, -3, 4])
arr[arr>=0] = arr[arr>=0] +10
arr[arr<0] = arr[arr<0] -10
arr

array([-11,  12, -13,  14])

In [120]:
arr = np.array([-1, 2, -3, 4])
np.where(arr >= 0, arr + 10, arr - 10)

array([-11,  12, -13,  14])

In [135]:
arr = [1, 2, 3, 4, 5]
np.random.choice(arr,5, replace=False)

array([1, 4, 3, 2, 5])

In [142]:
arr = np.array([1, 2, 3, 4, 5])
np.argmin(arr)

0

In [143]:
arr = np.array([1, 2, 3, 4, 5])
np.argmax(arr)

4

In [145]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr.sort()
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [146]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [148]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
np.vstack([arr1,arr2])

array([[1, 2],
       [3, 4]])

In [153]:
arr = np.array([ [1, 2], [3, 4] ])
arr.flatten()

array([1, 2, 3, 4])

#051~060

In [154]:
import pandas as pd
from pandas import Series

In [155]:
data = [100, 200, 300]
s = Series(data)
print(s)

0    100
1    200
2    300
dtype: int64


In [156]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s)

철수    100
영희    200
아름    300
dtype: int64


In [158]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data)
print(s)
s.index = index
print(s)

0    100
1    200
2    300
dtype: int64
철수    100
영희    200
아름    300
dtype: int64


In [160]:
score = {
    "철수": 100,
    "영희": 200,
    "아름": 300
}

s = Series(score)
print(s)

철수    100
영희    200
아름    300
dtype: int64


In [161]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.index)

Index(['철수', '영희', '아름'], dtype='object')


In [163]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.values)

[100 200 300]


In [166]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.to_dict())

{'철수': 100, '영희': 200, '아름': 300}


In [176]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
s.to_excel('data.xlsx')

In [177]:
data = pd.read_excel('data.xlsx', index_col=0)[0]
data

철수    100
영희    200
아름    300
Name: 0, dtype: int64

#061~070

In [182]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.dtype)

int64


In [181]:
data = [  10,  "가" ]
s = Series( data )
print(s.dtype)

object


In [184]:
data = [100, 200, 300]
index = ["철수", "영희", "아름"]
s = Series(data, index)
print(s.index.dtype)

object


In [199]:
data = {
    "2020-12-11": 73400,
    "2020-12-10": 72900,
    "2020-12-09": 73900,
    "2020-12-08": 71700,
    "2020-12-07": 72900
}
s = Series(data)
s.name = "종가"
s.index.name = "날짜"
s

날짜
2020-12-11    73400
2020-12-10    72900
2020-12-09    73900
2020-12-08    71700
2020-12-07    72900
Name: 종가, dtype: int64

In [201]:
data = {"apple": 1500, "banana": 3000}
s = pd.Series(data)
s.to_dict()

{'apple': 1500, 'banana': 3000}

In [203]:
data = {"apple": 1500, "banana": 3000}
s = pd.Series(data)
s.index.name='icecream'
s

icecream
apple     1500
banana    3000
dtype: int64

In [204]:
s = pd.Series(data=[1, 2, 3])
s.name = 'number'
s

0    1
1    2
2    3
Name: number, dtype: int64

In [207]:
s = pd.Series(data=[1, 2, np.NaN])
s

0    1.0
1    2.0
2    NaN
dtype: float64

In [210]:
s = pd.Series([1, 2, 3])
np.array(s.index)

array([0, 1, 2])

In [215]:
s = pd.Series([1, 2, 3])
print(s)
s.array

0    1
1    2
2    3
dtype: int64


<PandasArray>
[1, 2, 3]
Length: 3, dtype: int64